blank_issues_enabled: false  # "ë¹ˆ ì´ìŠˆ ë§Œë“¤ê¸°" ë²„íŠ¼ ë¹„í™œì„±í™”

contact_links:
  - name: ğŸ“„ í•œë™í”¼ë“œ ê´€ë ¨ ë¬¸ì˜ ë° í”¼ë“œë°±
    url: https://board.handong.app/feed/num/19
    about: "í•œë™í”¼ë“œ ê´€ë ¨ ë¬¸ì˜ì‚¬í•­ ë° í”¼ë“œë°±ì´ ìˆìœ¼ì‹œë©´ 'ë¬¸ì˜ì‚¬í•­ ë“±ë¡ ë°©ë²•'ì„ ì°¸ê³ í•´ì£¼ì„¸ìš”."
